version: '3.3'

services:
  mysql:
    image: library/mysql:8
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: api-dog
    ports:
      - 3306:3306
    volumes:
      - ~/docker/trading/mysql:/etc/var/mysql